modLoader="kotlinforforge" # or "javafml" depending on your Kotlin setup
loaderVersion="[1,)"
license="MIT"
[[mods]]
modId="hexical"
version="${version}"
displayName="Hexical (Forge)"
description="A fun addon containing genie lamps, mage blocks, specks, world scrying, and more!"
authors="Ruben Huizenga (Original by miyucomics)"
logoFile="assets/hexical/icon.png"

[[dependencies.hexical]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hexical]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hexical]]
    modId="hexcasting"
    mandatory=true
    versionRange="[0.11.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hexical]]
    modId="hexpose"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"